title: CS 6476 3D Football Play Reconstruction Project

description: >
  Kate Forsyth, Owen Velkoff, Dhruv Shah, Pranav Datta
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
